### ISSUE TITLE
Project Discussion

### ISSUE THREAD

**Issue by damienr74** [CSCI3130/sandbox#1]
# We Don't Have a Project Yet
------------------------------------------

The only proposal so far has been:
- Stock market prediction software

If you have other suggestions or want to discuss, please do so here.

**Comment by jonathanignacio** [comment]
CSCI 3130

*project may lean towards the development of a web app.

**Project Ideas:**

Stock Market Analysis (user recommendation/historical data) 

Home  Electricity Usage Monitoring Software (AI)

Interfacing with software radio (for use with satellites)

Facial Recognition (Machine Learning)

Image Quality Assessment for social media (rate images based on target audience) 

Medical Diagnosis Software (for specific body parts, especially with regards to cancer)

Politics 

Proline/Sports betting (baseball etc)

Bot to summarize News Articles (AutoTLDR)

League of Legends/Game Stat Tracker

ParaScope-like software

Wonderlist (TODO list)

Google Mom (auto todo list)

Raspberry Pi

**Comment by damienr74** [comment]
# We Have a Project!

Decided to go with: "Image Quality Assessment for social media (rate images based on target audience)"
